# toy_robot/interface.py
from abc import ABC, abstractmethod
from typing import Tuple

class RobotInterface(ABC):
    @abstractmethod
    def place(self, x: int, y: int, direction: str) -> None: ...
    @abstractmethod
    def propose_move(self) -> Tuple[int, int, str]: ...
    @abstractmethod
    def update_position(self, new_x: int, new_y: int) -> None: ...
    @abstractmethod
    def turn_left(self) -> None: ...
    @abstractmethod
    def turn_right(self) -> None: ...
    @abstractmethod
    def report(self) -> Tuple[int, int, str]: ...

class NavigationInterface(ABC):
    @abstractmethod
    def is_valid_position(self, x: int, y: int) -> bool: ...
